FROM oven/bun:1.1.44 AS builder

ENV CI=true

WORKDIR /app

COPY package.json bun.lock /

RUN bun install

COPY . .

RUN bun run build

FROM builder AS production

WORKDIR /app

COPY --from=builder /app/build /app/build

USER bun

EXPOSE $PORT

CMD ["bun","build/src/index.js"]
